AWSTemplateFormatVersion: "2010-09-09"
Description: Exemple de stack CloudFormation
Resources:
  MyBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      VersioningConfiguration:
        Status: Enabled